### ISSUE TITLE
Browserstack-sdk not compatible with robotframework 7.0

### ISSUE THREAD

**Issue by khoinguyen** [browserstack/robot-browserstack#20]
As the robotframework 7.0 was released, I cloned the repo with branch `sdk` and followed the document.

Then I got the following error:
```
[ ERROR ] Unexpected error: TypeError: bstack1ll1l111ll_opy_() takes 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/utils/application.py", line 81, in _execute
    rc = self.main(arguments, **options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/run.py", line 460, in main
    result = suite.run(settings)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/running/model.py", line 758, in run
    self.visit(runner)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/testsuite.py", line 420, in visit
    visitor.visit_suite(self)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/visitor.py", line 131, in visit_suite
    suite.suites.visit(self)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/itemlist.py", line 102, in visit
    item.visit(visitor)    # type: ignore
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/testsuite.py", line 420, in visit
    visitor.visit_suite(self)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/visitor.py", line 132, in visit_suite
    suite.tests.visit(self)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/itemlist.py", line 102, in visit
    item.visit(visitor)    # type: ignore
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/model/testcase.py", line 177, in visit
    visitor.visit_test(self)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/running/suiterunner.py", line 141, in visit_test
    self.context.start_test(data, result)
  File "/Users/khoinguyen/Workspace/tests/robot_web/venv/lib/python3.12/site-packages/robot/running/context.py", line 231, in start_test
    self.output.start_test(data, result)
TypeError: bstack1ll1l111ll_opy_() takes 2 positional arguments but 3 were given
```

After hours of tries and errors, I pinned robotframework to 6.1.1 and it works like a charm.

Recommendation:
For this repo: pin robotframework to 6.1.1

Other request: browserstack-sdk to support robotframework 7 (I can't find the repo of sdk to post the issue)

**Comment by karanshah-browserstack** [comment]
@khoinguyen This bug was fixed in browserstack-sdk version 1.19.10. You can upgrade to the latest version, and let us know if you still face any issues.
